services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - rabbitmq
