FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/Worker
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
COPY Worker/appsettings.json ./appsettings.json 
ENV ASPNETCORE_ENVIRONMENT=Development
ENTRYPOINT ["dotnet", "Worker.dll"]
